learningrate:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor

checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  monitor: val_f1_score
  mode: max
  verbose: true
  save_top_k: 1
  save_last: true
  auto_insert_metric_name: true
  filename: "best"

prediction:
  _target_: cd_mm_sits.callback.mm_solar_panel_clb.PlotMMSP
