defaults:
  - shallow_forecaster: rope_mm_shallow_forecast.yaml
  - _self_
_target_: cd_mm_sits.lightning_module.supervised_forecast.MMSupervisedForecast
pred_after_n: 5
compile: false
w_s2: 1
use_delta_times: false
