defaults:
  - shallow_forecaster: rope_mm_weather_forecast
  - _self_
_target_: cd_mm_sits.lightning_module.supervised_forecast.MonoMForecast
pred_after_n: 5
compile: false
use_delta_times: false
mod: ${datamodule.mod}
