_target_: cd_mm_sits.data.datamodule.solar_panels_datamodule.SPDataModule
dataset_path: ${server.path_sp_dataset}
path_dir_csv: ${server.path_sp_dataset}
max_len_s2: 8
batch_size: ${train.train_config.batch_size}
num_workers: 4
fold_expe: 1
crop_size: 64
