defaults:
- transform: mini_sqrt_s2_transform.yaml
_target_: cd_mm_sits.data.datamodule.monom_forecastDataModule.MonoMForecastDataModule
ziptif_paths: ${server.mm_forecast_dataset_mini}
batch_size: ${train.train_config.batch_size}
num_workers: 10
max_len: 15
crop_size: 64
mod: s2
consecutive_samples_in_test: true
