defaults:
  - _self_
  - metrics: forecast.yaml
path_expe: /lustre/fsn1/projects/rech/jmo/ubc65oh/trainings/isprs_mm_sp_benchmark_v4
path_dataset: /lustre/fsn1/projects/rech/jmo/ubc65oh/datasets/mm_solar_panel_zarr_orbites2
path_dir_csv: /lustre/fsn1/projects/rech/jmo/ubc65oh/datasets/mm_solar_panel_zarr_orbites2
max_len: 64
list_models_path: null
option: forecast
consecutive_samples_in_test: true
