_target_: cd_mm_sits.model.sse.LowResUnet
inplanes: ${shared.input_channels_s2}
planes: ${shared.d_model}
encoder_widths: [64, 64, 64, 128]
decoder_widths: [32, 32, 64, 128]
encoder_norm: batch
padding_mode: reflect
decoding_norm: batch
return_maps: false
skip_conv_norm: batch
